### ISSUE TITLE
手势视差翻页器实现

### ISSUE THREAD

**Issue by issaxite** [issaxite/issaxite.github.io#147]
# 一句话需求
实现一个轮播器，在轮播器上层有一个静止图层，不会随着轮播器翻页而偏移。

# 需求分析
### 以上需求可以拆分成两个小的需求：
- 实现一个轮播器；
- 做个静止图层。

### 问题
轮播器作为一个图层，静止图层是一个。
那么那个图层在上，那个在下？
- 1 轮播器在上，则静止图层被轮播器遮盖；
- 2 静止图层在上，则绑定在轮播器上的手势事件由于被静止图层在上而无法触发。

### 再细分需求
为了显示静止图层，那么静止图层一定是要在上的。那么就必须解决第2个问题，怎么触发轮播器的手势。
我们可以通过监听静止图层或者两图层容器的手势，然后映射到轮播器。

# 实现
### 1 实现一个轮播器
由于网上的轮播器插件的都是封装好的，触发事件比较麻烦，因此选择自己使用原生js实现一个。
实现轮播器的方案有很多中，比如改变`translate`属性的，也有先实现一个`scroll-view `，然后改变`scroll-view`的`scrollLeft`。我选用后者（单纯是因为我没有这样做，而且好像很有趣）。

### 那么就先实现一个`scroll-view`。

一般`scroll-view`都是纵向的，根据以上需求，我们就需要实现一个横向的`scroll-view`，具体实现如下
```html
<div id="app">
  <dl class="story">
    <dt></dt><dt></dt>
    <dt></dt><dt></dt><dt></dt>
    <dt></dt><dt></dt>
  </dl>
</div>
```
```css
*{ margin: 0;padding: 0; }
html,body{ height: 100%; }
::-webkit-scrollbar{ display: none; }

#app{ height: 100%;position: relative; }

#app > .story{ position: absolute;top: 0;right: 0;bottom: 0;left: 0; }

#app > .story{ 
  z-index: 1000; border: 1px solid;
  overflow-x: auto;overflow-y: hidden; white-space: nowrap;font-size: 0;letter-spacing: 0;
  /* translateZ是是为了开启硬件加速 */
  -webkit-transform: translateZ(0);
  -moz-transform: translateZ(0);
  -ms-transform: translateZ(0);
  -o-transform: translateZ(0);
  transform: translateZ(0);
}

.story > dt{ height: 100%;width: 100%;display: inline-block;vertical-align: top;position: relative; }
.story > dt:nth-of-type(1){ background-color: red; }
.story > dt:nth-of-type(2){ background-color: orange; }
.story > dt:nth-of-type(3){ background-color: yellow; }
.story > dt:nth-of-type(4){ background-color: green; }
.story > dt:nth-of-type(5){ background-color: cyan; }
.story > dt:nth-of-type(6){ background-color: blue; }
.story > dt:nth-of-type(7){ background-color: purple; }
```
核心css为
```css
overflow-x: auto;overflow-y: hidden; white-space: nowrap;
```
禁用块级元素的换行，依次达到横排的效果。[\[查看效果\]](https://jsfiddle.net/issaxite/ec6cmpkq/5/)
![](http://ohi69gup6.bkt.clouddn.com/scroll-view.gif)

### 监听静态手势
先向#app中添加静止图层
```
<div id="app">
  <dl class="mash">
    <img src="http://ohi69gup6.bkt.clouddn.com/005TGG6vly1fes9jc0kk0g30b40b40tv.gif">
  </dl>
  ...
</div>
```
然后，来分析一下轮播器的功能
- 1 向左，向右滑动翻页；
- 2 轮播器卡片手势跟随。

第1点的实现思路
获取手指 “触碰屏幕那刻” 和 “离开屏幕那刻” 的位置，根据以上两个位置判断翻页方向，要获取这两位置，就需要分别注册`touchstart`和`touchend`事件
```
// 触碰屏幕那刻位置
var touchStartX = e.changedTouches[0].pageX;
// 离开屏幕那刻位置
var touchEndX = e.changedTouches[0].pageX;
```
判断滑动方向
```
var isNext = touchEndX - touchStartX < 0;
```

知道翻页方向就可以进行翻页
翻页如上文所说，通过改变卡片容器的`scrollLeft`。这里的容器是`#app > .story`。
需要翻页，还需要知道两个属性：
- 每页宽度：可以通过`story.clientWidth`获取；
- 当前页：使用全局变量记录当前是第几页。
具体实现如下：
```js
var touchStartX = 0;
var currentPage = 1;
var mash = document.querySelector("#app > .mash");
var story = document.querySelector("#app > .story");
var screenWidth = story.clientWidth;

console.log(story.parentElement.children);

mash && mash.addEventListener('touchstart', function(e){
  var touch = e.changedTouches[0];
 touchStartX = touch.pageX;
}, false);

mash && mash.addEventListener('touchend', function(e){
  var touch = e.changedTouches[0];
  var touchEndX = touch.pageX;
  var isNext = touchEndX - touchStartX < 0;
  var oldCurrentPage = currentPage;
  var maxPage = story.children.length;
  var minPage = 1;

  currentPage = isNext ? currentPage + 1 : currentPage - 1;
  currentPage = currentPage > maxPage ? maxPage : currentPage;
  currentPage = currentPage < minPage ? minPage : currentPage;

  var targetScrollLeft = (currentPage - 1) * screenWidth;
  
  story.scrollLeft = targetScrollLeft;
});
```
[\[查看源码\]](http://jsbin.com/feganodaro/1/edit?html,css,js,output)（ps：要看效果需要使用移动设备模式）
![](http://ohi69gup6.bkt.clouddn.com/scroll-view2-iloveimg-compressed.gif)
