### ISSUE TITLE
圣杯布局的实现

### ISSUE THREAD

**Issue by issaxite** [issaxite/issaxite.github.io#158]
## 前言
在我看来，圣杯布局（由上至下：header，body，footer）可分成两类。
1. 只有body区域可以滑动；
2. 整个页面都可以滑动，在页面的body区域内容足够少时，它的表现和第一类表现相似；
以下是通用的html和css
```html
<div class="container">
  <div class="header"></div>
  <div class="body"></div>
  <div class="footer"></div>
</div>
```
```css
.container{
  height: 60vh;
  width: 100%;
  box-shadow: 0 0 5px 2px rgba(0,0,0,0.2);
}


.container > .header,
.container > .footer{
  width: 100%;
  height: 100px;
  background: rgba(181, 181, 181, 0.4);
}

.container > .body{
  width: 100%;
  background: #FFFFFF;
}
```

## flexBox实现圣杯布局
```css
/* flexBox */
.container{
  display: flex;
  flex-wrap: no-wrap;
  flex-direction: column;
  justify-content: space-between;
}


.container > .body{
  flex-grow: 1;
}

.container > .header,
.container > .footer{
  flex-grow: 0;
  background: rgba(181, 181, 181, 0.4);
}
```
![image](https://user-images.githubusercontent.com/25907273/37697653-fe350df8-2d18-11e8-887b-bcf7dacd59c8.png)
