### ISSUE TITLE
带圆角三角型的css实现

### ISSUE THREAD

**Issue by issaxite** [issaxite/issaxite.github.io#159]
## 前言
目标实现效果图如下：
>![image](https://user-images.githubusercontent.com/25907273/37703562-0e3d4126-2d31-11e8-858b-a26064adc055.png)

## 实现
```html
<i class="triangle triangle-up"></i>
<i class="triangle triangle-right"></i>
<i class="triangle triangle-down"></i>
<i class="triangle triangle-left"></i>
```
```css
.triangle{
  display: inline-block;
  font-size: 0;
  overflow: hidden;
}

.triangle:before{
  content: "";
  position: relative;
  display: inline-block;
  border: 25px solid transparent;
}

.triangle-up{
  position: relative;
  top: 2px;
}
.triangle-up:before{
  bottom: 2px;
  border-top-width: 0;
  border-bottom-width: 50px;
  border-bottom-color: rgba(181, 181, 181, 1);
}

.triangle-right{
  position: relative;
  right: 2px;
}
.triangle-right:before{
  left: 2px;
  border-right-width: 0;
  border-left-width: 50px;
  border-left-color: rgba(181, 181, 181, 1);
}

.triangle-down{
  position: relative;
  bottom: 2px;
}
.triangle-down:before{
  top: 2px;
  border-bottom-width: 0;
  border-top-width: 50px;
  border-top-color: rgba(181, 181, 181, 1);
}

.triangle-left{
  position: relative;
  left: 2px;
}
.triangle-left:before{
  right: 2px;
  border-left-width: 0;
  border-right-width: 50px;
  border-right-color: rgba(181, 181, 181, 1);
}
```

## 剖析
从以上代码中抽出一个triangle来剖析，就拿`triangle-down`来说。
一般css是不能画斜线的，因此得另辟蹊径。观以上实现代码，你会发现大量使用到border，其实这就是核心，也不复杂，一幅图便可说明
![image](https://user-images.githubusercontent.com/25907273/37704757-af6d62bc-2d34-11e8-9679-af9a877a5adc.png)

## 应用
>![image](https://user-images.githubusercontent.com/25907273/37703486-c5119146-2d30-11e8-9aaf-81fbd66dc317.png)
```html
<div class="bubble-box">
  <div class="bubble-box-hat">
    <i class="triangle triangle-up"></i>
  </div>
  <div class="bubble-box-body">i am isaac!</div>
</div>
```
```css
.bubble-box{
  font-size: 0;
  margin-top: 50px;
}

.bubble-box-hat{
  text-align: center;
}

.bubble-box-body{
  color: #FFFFFF;
  background: rgb(181, 181, 181);
  font-size: 28px;
  border-radius: 10px;
  padding: 100px;
  text-align: center;
}
```
