### ISSUE TITLE
sass：遍历lists

### ISSUE THREAD

**Issue by issaxite** [issaxite/issaxite.github.io#191]
```css
&.el-date-editor{
    $suffix-icon--width: 23px;
    $types:
      ('year' 74px),
      ('month' 98px),
      ('date' 122px),
      ('dates' 122px),
      ('week' 104px),
      ('datetime' 188px),
      ('datetimerange' 358px),
      ('daterange' 220px);
    @each $item in $types {
      &--#{nth($item, 1)} {
        &{ width: nth($item, 2); }
        &.suffix-icon{ width: nth($item, 2) + $suffix-icon--width; }
      }
    }

    &.suffix-icon .el-range__close-icon{ width: 25px; }
  }
```
